### ISSUE TITLE
Add Navigation Bar for Improved User Experience

### ISSUE THREAD

**Issue by Aryainguz** [Open-Source-Chandigarh/Euphoria-Check#1]
Enhance the user experience of our PERMA Meter web application by adding a navigation bar.
 Add important links in the navbar like "What is PERMA?", "About us" etc

**Comment by Kartikey-Bartwal** [comment]
I'm on it

**Comment by Aryainguz** [comment]
> I'm on it

Go ahead @Kartikey-Bartwal 🚀 and feel free to connect if you need any help!
