### ISSUE TITLE
Screenshot image

### ISSUE THREAD

**Issue by bhumika-1127** [Open-Source-Chandigarh/Euphoria-Check#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the image which is screenshotted doesn't shows 'P','E','R','M' logo in the ss. I can fix this under GSSOC'24. @Aryainguz  Kindly assign this task to me.
![screenshot](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/137604220/82050d28-054a-421b-896e-65842f240f3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
Go ahead on this @bhumika-1127

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Ananya-Nair20** [comment]
Hello @Aryainguz. If this issue persists, I would like to work on this issue.
