### ISSUE TITLE
Feat: Change the color of selected answer

### ISSUE THREAD

**Issue by AbhiJay1287** [Open-Source-Chandigarh/Euphoria-Check#108]
### Describe the feature

When the user selects any of the 2 options the selected optioned should be colored which enhances the visual appearance of the Questions 

### Add ScreenShots

![Screenshot (126)](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/105973197/aa60f97d-afd7-4da2-86c4-439a4cc408c9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
go ahead @AbhiJay1287
