### ISSUE TITLE
Feat: Adding scroll to top feature button

### ISSUE THREAD

**Issue by reshamsai150** [Open-Source-Chandigarh/Euphoria-Check#110]
### Describe the feature

The scroll-to-top button appears when the user starts scrolling down the page.
When clicked, it smoothly scrolls the page back to the top.

### Add ScreenShots

![Screenshot 2024-05-16 143447](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/164533685/31cb4f08-ebda-499e-a656-a6bf247dada3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
it's already implemented
