### ISSUE TITLE
Feat: Adding Animated icons in scroll top button

### ISSUE THREAD

**Issue by SadafKausar2025** [Open-Source-Chandigarh/Euphoria-Check#114]
### Describe the feature

this features gives new good look to the questions page

### Add ScreenShots

please watch this vedio in full screen to see top arrow icon 

https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/137484958/2cf89d6a-6508-442f-994e-d85bed0131b1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by masterboy376** [comment]
Hello @Aryainguz I would like to work on the issue under GSSoC'24. I have successfully completed the repo setup on my local machine.

**Comment by Aryainguz** [comment]
go ahead @masterboy376
