### ISSUE TITLE
Feat:Adding share button on the Result page

### ISSUE THREAD

**Issue by mondalsurojit** [Open-Source-Chandigarh/Euphoria-Check#118]
### Describe the feature

There should be a button on the result page to directly share the result as a screenshot to different social medias

### Add ScreenShots

![Screenshot (263)](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/114282267/a3b0129e-edde-43b5-bc01-1c1dff8a8445)

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
go ahead @mondalsurojit

**Comment by mondalsurojit** [comment]
@Aryainguz Sir, I have already solved this issue and this is the PR link:
https://github.com/Open-Source-Chandigarh/Euphoria-Check/pull/155#event-13009289108
I don't know why, its not getting reflected in the leaderboard. Please look into the matter. 
Also, one more request, can you please mark it as a level-2 issue😊🙏
