### ISSUE TITLE
Missing LEARN.md_DOC:

### ISSUE THREAD

**Issue by Meetjain1** [Open-Source-Chandigarh/Euphoria-Check#142]
### What's wrong with the existing documentation

Learn.md file is missing in our current repository 
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository.

@Aryainguz assign this issue to me I will add it,
I am working under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
go ahead @Meetjain1

**Comment by Meetjain1** [comment]
@Aryainguz have a look on pr #149
