### ISSUE TITLE
BUG: Overlapping

### ISSUE THREAD

**Issue by sharmi4590** [Open-Source-Chandigarh/Euphoria-Check#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey
The goback button on the results page is being overlapped on smaller dimensions.
![Screenshot (475)](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/102676949/252b9fc5-fd61-4062-b507-22dac83d13f1)
![Screenshot (476)](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/102676949/ed4b4b31-f020-420a-b963-7d66dba1fdbf)
![Screenshot (477)](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/102676949/16b76a46-e91c-4f71-8a57-0c4d09b5825c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
Go ahead on this @sharmi4590
