### ISSUE TITLE
Feat: submit button css

### ISSUE THREAD

**Issue by Rags-Mishra** [Open-Source-Chandigarh/Euphoria-Check#160]
### Describe the feature

The 'submit and calculate' button on smaller screen could be more properly placed. In desktop view it is fine but in mobile view it is not looking good.

## Solution
- For mobile screen the button can be made to be of full length.
- The test can be made justified to look visually appealing.

### Add ScreenShots

![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/83007531/f7789fec-b258-44a4-88a8-a5d64dc437b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
Go ahead @Rags-Mishra

**Comment by Rags-Mishra** [comment]
Ok.
