### ISSUE TITLE
DOC: Addition of COntributor's logo's to Readme.md file

### ISSUE THREAD

**Issue by Anjaliavv51** [Open-Source-Chandigarh/Euphoria-Check#161]
### What's wrong with the existing documentation

Ntg wrong Addition of COntributor's logo's to Readme.md file

### Add ScreenShots

![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/154777864/ec4f349e-9932-4e1c-8c0c-7c078ba2b34f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
Go ahead @Anjaliavv51

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
@Aryainguz would also allow me to add no of forks stars PR closed open issue count also.

**Comment by Anjaliavv51** [comment]
@Aryainguz please review the PR
