### ISSUE TITLE
Feat:Add a scale as the user progresses the test

### ISSUE THREAD

**Issue by AkhilaSunesh** [Open-Source-Chandigarh/Euphoria-Check#166]
### Describe the feature

Add a scale as the user progresses the test
Kindly assign this issue to me

### Add ScreenShots

![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/140897461/4a416738-4902-493c-8931-e3e59c70d732)
or 
![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/140897461/0de3216c-e2d1-4a43-95b1-ff8662c2f6ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
Go ahead @AkhilaSunesh
