### ISSUE TITLE
Feat: Add Emojis to Questions

### ISSUE THREAD

**Issue by revanth1718** [Open-Source-Chandigarh/Euphoria-Check#195]
### Describe the feature

I propose enhancing the user interface of the website by adding emojis to each question. This will make the questionnaire more engaging and visually appealing, thereby improving the user experience.

### Add ScreenShots

![Screenshot (606)](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/109272714/7fe511ed-aceb-4c9e-9045-575441c3eee2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aastha204** [comment]
### Describe the feature
Making question page visually more appealing

### Add screenshot
N/A

### Record

- I agree to follow this project's Code of Conduct
- I'm a GSSOC'24 contributor
- I want to work on this issue

**Comment by Aryainguz** [comment]
Go ahead @Aastha204
