### ISSUE TITLE
Feat:Addition of preloader

### ISSUE THREAD

**Issue by Anjaliavv51** [Open-Source-Chandigarh/Euphoria-Check#216]
### Describe the feature

It gives idea to the user , whether page is loading or not.

### Add ScreenShots

Sample Example

![image](https://github.com/user-attachments/assets/2e0e7765-66e7-4966-8029-5cb9166a3622)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anjaliavv51** [comment]
@Aryainguz please assign me this issue under GSSOC.

**Comment by vivi2004** [comment]
@Aryainguz    please assign  me this issue  under girlsScript summer of code

**Comment by Anjaliavv51** [comment]
@Aryainguz please assign me this issue

**Comment by Aryainguz** [comment]
Go ahead @Anjaliavv51

**Comment by Anjaliavv51** [comment]
@Aryainguz Okay
