### ISSUE TITLE
Create 'About' Page 

### ISSUE THREAD

**Issue by Aryainguz** [Open-Source-Chandigarh/Euphoria-Check#3]
This page will serve as a dedicated space to provide users with essential information about the project, its mission, and PERMA model.
Also add information about Open Source Chandigarh and our vision in open source space

**Comment by KartikeyBartwal** [comment]
made a PR on this issue

**Comment by KartikeyBartwal** [comment]
made a PR on this issue https://github.com/Open-Source-Chandigarh/Euphoria-Check/pull/18

**Comment by rudrakushwaha** [comment]
@Aryainguz I would like to work on this issue. Is this issue still open?

**Comment by Aryainguz** [comment]
Yes @rudrakushwaha go ahead !

**Comment by rudrakushwaha** [comment]
Thank you

**Comment by rudrakushwaha** [comment]
@Aryainguz I have successfully created the about page and opened a pull request please review it.
