### ISSUE TITLE
Enhancing Design of Happiness Assessment Page

### ISSUE THREAD

**Issue by Prithwi32** [Open-Source-Chandigarh/Euphoria-Check#43]
Key points achieved by solving this issue:
*Visually appealing UI for user
*Responsiveness
*Adding Proper Color and font size

**Comment by Prithwi32** [comment]
@Aryainguz Please could you assign me this issue under GSSoC'24

**Comment by Aryainguz** [comment]
Sure go ahead @Prithwi32

**Comment by Prithwi32** [comment]
@Aryainguz could u add gssoc and level label for this issue

**Comment by Aryainguz** [comment]
sure go ahead @Prithwi32

**Comment by Prithwi32** [comment]
@Aryainguz Hello, made PR could you check it once...Thank YOU

**Comment by Prithwi32** [comment]
> @Aryainguz Hello, made PR could you check it once...Thank YOU

@Aryainguz PR merged still issue open...and could u add label for level

**Comment by Prithwi32** [comment]
> > @Aryainguz Hello, made PR could you check it once...Thank YOU
> 
> @Aryainguz PR merged still issue open...and could u add label for level

@Aryainguz look into it..and also please add level and gssoc label for both PR and Issue..and close this issue
