### ISSUE TITLE
Uneven font size and border radius on landing page

### ISSUE THREAD

**Issue by Ani1702** [Open-Source-Chandigarh/Euphoria-Check#47]
The landing page has circles marked as PERMA. The border radius of circles is uneven. Also the font is not properly aligned.

**Comment by Ani1702** [comment]
@Aryainguz I am interested in resolving it. Kindly assign it to me under GSSoC'24.

**Comment by Aryainguz** [comment]
Sure go ahead @Ani1702

**Comment by Ani1702** [comment]
Hey, I have created a PR #59 to address the issue.

**Comment by Aryainguz** [comment]
Great and thanks for your valuable contribution @Ani1702
