### ISSUE TITLE
Implement Common Error Page for Random Route

### ISSUE THREAD

**Issue by Ani1702** [Open-Source-Chandigarh/Euphoria-Check#48]
Random non-existent routes currently lacks a common error page, leading to inconsistent user experiences when errors occur. This enhancement would improve user understanding of encountered errors and contribute to a more professional and user-friendly experience overall.

**Comment by Ani1702** [comment]
@Aryainguz I would like to add a custom error page. Kindly assign it to me under GSSOC'24

**Comment by ShreyashKathade** [comment]
Can you assign the issue under GSSoC'24

**Comment by Aryainguz** [comment]
Go ahead @ShreyashKathade

**Comment by Missdivyaa** [comment]
@Aryainguz  I want to work on this issue. kindly assign me this issue under gssoc'24
