### ISSUE TITLE
Arrow button which take up to the top

### ISSUE THREAD

**Issue by jaydeep099** [Open-Source-Chandigarh/Euphoria-Check#49]
There could be an arrow button which will take it to the top of the page so user could some scrolling. 
Please assign this issue to me i will work upon under gssoc 2024 as in contributor.

**Comment by ayushrskiaa** [comment]
can I do it? will it be count in GSSOC?

**Comment by CS251000** [comment]
Request for assignment of this issue.
I am experienced in frontend development and believe that i will write an easy solution for the given problem

**Comment by Chaitanya-sesha-govind** [comment]
please add Gssoc label

**Comment by Aryainguz** [comment]
@jaydeep099 you’re the first so go ahead on this

**Comment by Kashif581** [comment]
Hi Aryainguz!
I hope your doing well. I have add a feature of button that take user to the top of the page. check out my pull request. 
Thank you

**Comment by jaydeep099** [comment]
@Aryainguz  I will complete asap

**Comment by Aryainguz** [comment]
completed by @Kashif581
