### ISSUE TITLE
Improve Personalized Emails Content 

### ISSUE THREAD

**Issue by Aryainguz** [Open-Source-Chandigarh/Euphoria-Check#5]
Users receive personalized emails helping them improve the selective PERMA score they lack in, improve the content and try adding more personalization in app.js file

**Comment by archana423** [comment]
@Aryainguz I would like to work on this issue. Please assign this to me

**Comment by archana423** [comment]
hey @Aryainguz I have changed the format and added username in the email to make it look more personalized. Please review it and merge it with "hacktoberfest-accepted" label.
