### ISSUE TITLE
Bug found ! Default clear occurs

### ISSUE THREAD

**Issue by Sushanth-Hebri** [Open-Source-Chandigarh/Euphoria-Check#50]
**Hello there, i found a bug in "questions page"**
When user answers few questions and try to submit the form , it shows error and shows message to fill all questions,
but the questions which users previously selected all will be erased !

I hereby requesting you to assign this task to me as part of GSSOC'24

thank you ❤️
![Screenshot 2024-05-10 162630](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/117469085/2a3ae19f-06e7-4b7c-9ad0-7d36f364c892)

**Comment by Sushanth-Hebri** [comment]
Kindly assign this bug issue solving task to me ❤️

**Comment by Aryainguz** [comment]
sure go ahead and help us resolve this @Sushanth-Hebri

**Comment by Sushanth-Hebri** [comment]
Fixed it , now it works well ❤️

**Comment by Aryainguz** [comment]
great work @Sushanth-Hebri

**Comment by Sushanth-Hebri** [comment]
@Aryainguz Hi , gssoc label and level of work label is not assigned to this issue , the PR is already merged. Kindly consider assigning the Labels as its my first open source contribution.
thank you 
❤️
