### ISSUE TITLE
Responsive result page

### ISSUE THREAD

**Issue by MitulSonagara** [Open-Source-Chandigarh/Euphoria-Check#55]
Particularly I opened this website on my mobile through your deployment link and i checked my score. but the result page is vary bad in responsive UI. That go back button is hiding behind the scorecard. So i will make full website as responsive. I have experience in CSS and Tailwind. I have confidence that i will make this website fully responsive. 

I am contributing under GSSOC'24.

**Comment by Aryainguz** [comment]
sure go ahead @MitulSonagara

**Comment by MitulSonagara** [comment]
Thank you for merging this and appreciate my work.
@Aryainguz can you add level 1 label for points in gssoc'24 or points are already given.
