### ISSUE TITLE
Add more questions related to PERMA model

### ISSUE THREAD

**Issue by Aryainguz** [Open-Source-Chandigarh/Euphoria-Check#6]
Try adding more relevant questions and be sure those questions are based on PERMA model.
Improving Accuracy should be the priority

**Comment by pinak22dhir** [comment]
we can add questions @Aryainguz like
on positive emotions :
how often you face negative emotions and  relax yourself within certain time  limit?
on engagement:
how often you start the conversations with your classmate?
how often you participate  in random university events?
how often you engage yourself in sports, dance or any other workout activity?
on relationships:
how often you talk to yourself by looking at mirror or journaling?
how often you do self care taking balanced diet doing skin care?
on achievements:
are you satisfied with your achievements?
have you decided a path to achieve your next goal?

**Comment by Aryainguz** [comment]
Great thought @pinak22dhir would you like to work upon this ? And if yes then be sure that the questions are based on PERMANENT model are from trustable existing PERMANENT related platforms or articles.

**Comment by pinak22dhir** [comment]
yes @Aryainguz i will like to work on this issue

**Comment by Aryainguz** [comment]
> yes @Aryainguz i will like to work on this issue

Okay Pinak go ahead and feel free to connect if you need any help!
