### ISSUE TITLE
feature : Description of PERMA terms on landing page

### ISSUE THREAD

**Issue by ritu713** [Open-Source-Chandigarh/Euphoria-Check#61]
On the landing page, there are icons of each letter of PERMA. 
Hovering/Clicking on this letter gives you a brief description of what the term stands for. 
_The same can be done on the results page as well._

Benefits : 
Lets assessment takers know what values are being evaluated
Increases knowledge about PERMA itself.

**Issue created for GSSOC '24**

**Comment by Aryainguz** [comment]
nice idea go ahead @ritu713

**Comment by vanirastogi** [comment]
Can You assign it to me under GSSoC'24 label

**Comment by ritu713** [comment]
@vanirastogi I'm working on it already :)

**Comment by ritu713** [comment]
Hey @Aryainguz !
I've submitted a pull request regarding this feature. Please review :)
