### ISSUE TITLE
Improve questions page layout

### ISSUE THREAD

**Issue by Aryainguz** [Open-Source-Chandigarh/Euphoria-Check#7]
Help us improve the questions page layout and make it look even better visually, make sure the responsiveness of the application as well.

**Comment by SanjanaReddy7707** [comment]
@Aryainguz 
I am interested to work on this issue
can you plz assign this to me
thank you!

**Comment by Aryainguz** [comment]
Okay @SanjanaReddy7707 go ahead and feel free to connect if you need any help!

**Comment by SanjanaReddy7707** [comment]
Hey @Aryainguz 
The provided code is in EJS, which I'm not really familiar with. So, I won't be able to take this one.
I'm sorry. I should have checked before.

**Comment by Aryainguz** [comment]
No problem @SanjanaReddy7707

**Comment by rudrakushwaha** [comment]
hey @Aryainguz please assign the issue to me. I want to work for it.

**Comment by rudrakushwaha** [comment]
hey @Aryainguz I have changed the layout by improving CSS and opened a pull request. Please review it and merge it with "hacktoberfest-accepted" label
