### ISSUE TITLE
Feat:Instead of arrow add text enter 

### ISSUE THREAD

**Issue by SalehaTabassum** [Open-Source-Chandigarh/Euphoria-Check#72]
### Describe the feature

As we can see that here we have arrow to proceed but it would be better to have a text like enter on the button it would look more good .

Please assign this issue to me under GSSOC 2024

### Add ScreenShots

![Screenshot_2024-05-12-11-51-39-28_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/169278740/50e43679-e78f-4964-9868-8e699a621cc4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SalehaTabassum** [comment]
@Aryainguz please assign this issue to me

**Comment by Aryainguz** [comment]
@SalehaTabassum arrow is better I think
