### ISSUE TITLE
Refactor: generate questions using iteration on a JSON file/object

### ISSUE THREAD

**Issue by 0adiy** [Open-Source-Chandigarh/Euphoria-Check#79]
### Describe the feature

The view `questions.ejs` contains repetitive code, with templating this can be simply resolved and iteration can be used to construct all the questions that is easier to maintain and more readable

### **Suggestion** is to make this part a separate template and reuse it
```html
 <div class="radio-input">
      <div class="info">
        <span class="question">How often do you find yourself happy?</span>
        <span class="steps">1/20</span>
      </div>
      <div class="radio-options">
        <input type="radio" id="value-2" name="avalue" value=5>
        <label for="value-2">Frequently</label>

      </div>
      <div class="radio-options">
        <input type="radio" id="value-1" name="avalue" value=0>
        <label for="value-1">Rarely</label>

      </div>
    </div>
```

### Add ScreenShots

![image](https://github.com/Open-Source-Chandigarh/Euphoria-Check/assets/64973364/a19cc64d-3269-4d80-9440-54a9d2fc81c3)
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aryainguz** [comment]
Great for pointing this crucial, will really appreciate if you do this need extra attention @0adiy
